### ISSUE TITLE
Access to XMLHttpRequest at 'waifu.pics' has been blocked by CORS policy

### ISSUE THREAD

**Issue by ksixen** [Waifu-pics/waifu-api#29]
I getting this error
![Screenshot_5](https://user-images.githubusercontent.com/38946653/117540754-7607ad00-b032-11eb-9c4d-8bf12e6fbaf1.png)

I'm using axios with react. I tried use Express and Cors, but its not helped.

Code:
```JavaScript
import axios from 'axios';
function App () {
const [picture, setPicture] = useState({ url: '' });
let onNextBtnClick = () => {
    axios.get(`https://api.waifu.pics/sfw/waifu`)
      .then(response => setPicture({ url: response.data.url }))
  }
return <img src={picture.url} alt='anime-picture' />
}
```

**Comment by HolyArseny** [comment]
Have same problem

**Comment by bhavesh-chaudhari** [comment]
@HolyArseny @ksixen Did you figure this out ?
@Riku32 I am having the same issue. Can you help here ?

**Comment by ksixen** [comment]
> @HolyArseny @ksixen Did you figure this out ?
> @Riku32 I am having the same issue. Can you help here ?

I used it to bypass it, but it's some times work sometimes doesn't
```
https://api.codetabs.com/v1/proxy?quest=https://api.waifu.pics/sfw/waifu
```

**Comment by Riku32** [comment]
Should be fixed now internally. Try again
