### ISSUE TITLE
api.waifu.pics/many/... returns Method Not Allowed

### ISSUE THREAD

**Issue by irevenko** [Waifu-pics/waifu-api#30]
Can not access ```https://api.waifu.pics/many/sfw/waifu```
![image](https://user-images.githubusercontent.com/44785096/117636040-42fa1200-b135-11eb-8aaa-202a94bc5bfb.png)

**Comment by irevenko** [comment]
oops it is ```POST``` request

**Comment by Riku32** [comment]
Yeah it's post because of the exclude. Generally used for front page
