### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by bhavesh-chaudhari** [Waifu-pics/waifu-api#31]
I am getting a CORS error when trying to access the API -

Error message :
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.waifu.pics/sfw/waifu. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘’).`

This is the code i am using to fetch the image url :
```
function get_animes() {
  fetch("https://api.waifu.pics/sfw/waifu")
    .then((res) => res.json())
    .then((data) => {
      console.log(data);
    });
}
```
@Riku32

**Comment by Riku32** [comment]
This should be fixed now

**Comment by bhavesh-chaudhari** [comment]
> 
> 
> This should be fixed now

Yes this issue has been solved now. Thank you very much !
