### ISSUE TITLE
"Many" returns error 400

### ISSUE THREAD

**Issue by umZeroo** [Waifu-pics/waifu-api#37]
A **POST** request to `https://api.waifu.pics/many/sfw/category` returns Response code 400 with message:
```json
{
    "message": "that was not a valid json body"
}
```

Recording:
https://user-images.githubusercontent.com/72270756/123290185-b2ce2b80-d52e-11eb-83cf-8d09e1eb8261.mp4

**Comment by Riku32** [comment]
Many is a post request that needs the `exclude` field which lets you exclude a certain image/s. Make sure it is an empty array at least.
