### ISSUE TITLE
add list of categories to api

### ISSUE THREAD

**Issue by raventhecat333** [Waifu-pics/waifu-api#40]
if the api is called it simply says {"message":"Not Found"}
is there a way to get all the categories?

**Comment by Riku32** [comment]
Please check the documentation. 
https://waifu.pics/docs

**Comment by raventhecat333** [comment]
ok so poor wording on my part, what i meant was if an invalid category is called is there a way to return an error with the categories in a list

**Comment by Riku32** [comment]
https://api.waifu.pics/endpoints
