### ISSUE TITLE
Question about multiple images

### ISSUE THREAD

**Issue by MmesasMOB** [Waifu-pics/waifu-api#41]
Hi, I'm new to programming, I'm having an error when using the API to get multiple images.

![image](https://user-images.githubusercontent.com/89486114/130686212-d1187303-198a-418a-8714-4227de309738.png)

![image](https://user-images.githubusercontent.com/89486114/130686248-9b33beec-82ce-46f3-b243-0e2ca7e5b0cd.png)

I appreciate if you can help me! Ty

**Comment by Riku32** [comment]
You need to at minimum provide an empty array called `exclude`. This is if you want to filter out some images.

**Comment by ladnooo** [comment]
how to use exclude
