### ISSUE TITLE
Husbando

### ISSUE THREAD

**Issue by ShinNouzen** [Waifu-pics/waifu-api#45]
Please create a page for husbando too.. please. There are no husbando api, so please accept my request.

**Comment by Riku32** [comment]
If you are willing to send over 50 example images per endpoint in a zip you want created and list all endpoints in this issue. I will add it to the API and upload those 50 first images.

**Comment by ShinNouzen** [comment]
How could i send the zip file to you?

**Comment by Riku32** [comment]
Just upload it anywhere and send a link, or git issues can attach files

**Comment by ShinNouzen** [comment]
[Husbando.zip](https://github.com/Waifu-pics/waifu-api/files/7174529/Husbando.zip)
Here's the zip file. It has  90+ husbando images.

**Comment by ShinNouzen** [comment]
Umm.. Have you created the page?

**Comment by ShinNouzen** [comment]
Please reply if you can hear me

**Comment by Riku32** [comment]
Just looked at the images. They are pretty low-res so I cant really commit them. Try to find images on booru sites with high-resolution. Take the waifu endpoint as an example.

**Comment by ShinNouzen** [comment]
https://www.mediafire.com/file/mpeagyirw82izmh/Husbando.zip/file
Here's the link. I couldn't attach the file here as it was too big. Please download from here.

**Comment by ShinNouzen** [comment]
Is this gonna be okay?

**Comment by ShinNouzen** [comment]
Please reply

**Comment by ShinNouzen** [comment]
Hello?

**Comment by ShinNouzen** [comment]
well

**Comment by Riku32** [comment]
Sorry, the images are supposed to be cute but most of them were just stuff like SAO type stuff, once again the current pics on waifu endpoint are an example
