### ISSUE TITLE
API is down

### ISSUE THREAD

**Issue by sireeshdevaraj** [Waifu-pics/waifu-api#53]
502 bad gateway error

**Comment by JSH32** [comment]
Damn, first downtime in like two years. Yeah im rebooting it I don't know what happened. I think its because we recently moved off GCP

**Comment by JSH32** [comment]
Fixed downtime and moved back to Google while I sort stuff out. When did the downtime start?
@sireeshdevaraj

**Comment by sireeshdevaraj** [comment]
dont know the exact time, but it happened for a hour!!

**Comment by JSH32** [comment]
Ah well, fixed now. Closing this, lmk if anything else happens

**Comment by sireeshdevaraj** [comment]
yeah Sure
