### ISSUE TITLE
NSFW Results in SFW Endpoint?

### ISSUE THREAD

**Issue by Abadima** [Waifu-pics/waifu-api#54]
I've implemented waifu.sfw("neko") into the code, but some results are showing NSFW.

**Comment by sireeshdevaraj** [comment]
yeah,same,I just came to report it xD
neko is giving NSFW nekos
"https://i.waifu.pics/mmFOhuL.jpg"" Got this one in SFW category

**Comment by Sirspam** [comment]
Bumping this. Went through the sfw neko category and found multiple instances of nsfw images.
Dumping my little list of the images in case it's helpful

https://i.waifu.pics/DFzhI9P.jpg
https://i.waifu.pics/AZMKAcI.jpg
https://i.waifu.pics/HXBm9Y5.jpg
https://i.waifu.pics/rk3ZiFp.jpg
https://i.waifu.pics/2jqJur7.png
https://i.waifu.pics/mY03mon.jpg
https://i.waifu.pics/mmFOhuL.jpg

**Comment by JSH32** [comment]
There should be 11 images in there. I think something got accidentally sent to the wrong endpoint. Let me delete and look for the others

**Comment by JSH32** [comment]
Images have been moved, don't know how that slipped in there but I looked in the verify log and someone verified it. I'm putting an undo or action log feature in the roadmap. Plan to work on this over the summer. For now removed all NSFW in that category
