### ISSUE TITLE
Downtime, 502 bad gateway

### ISSUE THREAD

**Issue by SammyWhamy** [Waifu-pics/waifu-api#57]
Not sure if you're already aware and/or if this is something I should open a ticket for, but the API has been down for roughly 2 hours already.

Along with this, maybe it'd be nice to have a status page or more direct way to communicate downtime of the API

**Comment by JSH32** [comment]
I think something on cloudflare broke. Access at http://207.244.248.212:9001 if you need it for now. Will update soon

**Comment by SammyWhamy** [comment]
While `http://207.244.248.212:9001/` gives a proper JSON response, `http://207.244.248.212:9001/sfw/waifu` (And any other image endpoint) just loads forever for me, so might be an actual issue with the backend?

**Comment by JSH32** [comment]
Use /api after the port

**Comment by JSH32** [comment]
Original route should work now. I reverted everything to Google cloud so it should be super stable. Was running on contabo but I think the certificate got messed up after a year or two. Try the original link now

**Comment by SammyWhamy** [comment]
`http://207.244.248.212:9001/api/sfw/waifu` gives me a `{"message": "Not Found"}`
`http://207.244.248.212:9001/sfw/waifu` gives a `{"message": "there was an issue processing this request"}` after a long loading time.
`https://waifu.pics/` still going to a "Are you lost" screen

I assume it might just take a bit to resolve after reverting to gcp? I'll try again in a while, thank you for working on it! Let me know if I should try anything else!

**Comment by SammyWhamy** [comment]
`https://api.waifu.pics/sfw/hug` now gives me a Cloudflare 524 Timeout Error or a blank page with "Rate exceeded."

**Comment by JSH32** [comment]
Sorry, was taking a test so couldn't get to much stuff. It should be fixed now. I'll be redoing infrastructure soon to make sure this does not happen again. Keeping this open for a few hours just to make sure nothing else arises

**Comment by JSH32** [comment]
New information ![Screenshot_20220414-113801_Gmail.png](https://user-images.githubusercontent.com/51795153/163434377-21fc635f-4b04-43a7-8d2d-d84ff79bdfa2.png)
Fuck oracle. They took the db servers ip, fixed permanently

**Comment by SammyWhamy** [comment]
Ah that sucks, thank you for looking into it! Working as expected again <3

**Comment by Monix362** [comment]
@JSH32 Is there any updated information available regarding the reappearance of this issue?

![image](https://user-images.githubusercontent.com/61246713/217212871-d782ffd2-b46c-4de1-81ea-37c6f644392c.png)
![image](https://user-images.githubusercontent.com/61246713/217212981-455ff784-fd20-4463-8e6a-78d762a536c4.png)

**Comment by JSH32** [comment]
Back up, db server shut down for some reason

**Comment by Monix362** [comment]
@JSH32 Hello! API is not working again...
![image](https://user-images.githubusercontent.com/61246713/228313739-af67d316-32ba-4e5d-97db-71411a64a1ab.png)
![image](https://user-images.githubusercontent.com/61246713/228313757-5964d0d9-978f-4831-9b72-dc4afedd5e31.png)

**Comment by JSH32** [comment]
Handling it rn, the db server went offline. I need to stop using oracle cloud after this happened for the second time. Sorry bout that
