### ISSUE TITLE
SFW "k" category not found

### ISSUE THREAD

**Issue by tsuji-riya** [Waifu-pics/waifu-api#58]
I found "k" category on API Docs, but it didn't worked.
Was it written by mistake?
![ss1](https://user-images.githubusercontent.com/99951138/163546606-a312d1ea-926a-494c-ab44-a747cc2ad283.png)
![ss2](https://user-images.githubusercontent.com/99951138/163546612-f43b7e61-a1dc-452d-b18b-dba9f3f8910d.png)

**Comment by tsuji-riya** [comment]
ugh.. 
"didn't worked." → "didn't work."

**Comment by JSH32** [comment]
Fixed
