### ISSUE TITLE
Happy Category is Not Found

### ISSUE THREAD

**Issue by sireeshdevaraj** [Waifu-pics/waifu-api#59]
{"message":"Not Found"}
when I try to access the end point

**Comment by SammyWhamy** [comment]
The endpoints
`/sfw/kill`
`/sfw/happy`
`/sfw/wink`
`/sfw/poke`
`/sfw/dance`
`/sfw/cringe`
Are all returning a 404 Not Found with the above mentioned JSON response, I assume this has something to do with the recent revert to GCP (#57)

It almost seems like the array of endpoints was cut off in the middle of the `kill` endpoint, as theres now a `k` endpoint (#58) mentioned where `kill` was before in the array (`/endpoints`)

**Comment by JSH32** [comment]
FIxed

**Comment by SammyWhamy** [comment]
Thank you! <3
