### ISSUE TITLE
Json error when posting with empty body to /many/ urls 

### ISSUE THREAD

**Issue by Nekidev** [Waifu-pics/waifu-api#64]
# Error

An error is returned when sending an empty body to any `/many/` API URL. (ex: https://api.waifu.pics/many/sfw/waifu).

```json
{
    "message": "that was not a valid json body"
}
```

This is not the expected behaviour because no `Content-Type` header is present in the request, and therefore no body should be parsed. However, this still happens. I have not read the source code, but I believe it is probably an error when trying to parse an object from the request looking for the `exclude` filter.

# Workaround

The API is still usable by sending an empty JSON object body. However, how I have already said, the body should not be considered JSON unless an explicit `Content-Type: application/json` header is set.

**Comment by de-padua** [comment]
I have this exact same issue,but I can't fix it even trying this  **_Temporary fix_**
edit: i managed to  make it work with the  **_Temporary fix_** ,if anyone is struggling like i did,just do like this >
            _method : 'POST',
            mode: 'cors',
            cache: 'default',
            headers: {
                'Content-Type': 'application/json'
                // 'Content-Type': 'application/x-www-form-urlencoded',
              },
            body: JSON.stringify({})_

**Comment by plrz** [comment]
do you guys know which application you guys used to do this?

**Comment by Nekidev** [comment]
> do you guys know which application you guys used to do this?
> 

What do you mean by "this"?

**Comment by plrz** [comment]
like how do you do the fix, im using postman

**Comment by Nekidev** [comment]
> like how do you do the fix, im using postman

Its not like you fix it and you actually starts working. Its a workaround. You can send plain `{}` in the body and it will work. You dont need a specific platform for that, you just send it.
