### ISSUE TITLE
"Method Not Allowed"

### ISSUE THREAD

**Issue by Akshar062** [Waifu-pics/waifu-api#75]
i have tried to call [URL](https://api.waifu.pics/many/sfw/neko) i am gatting

`{
"message": "Method Not Allowed"
}`

**Comment by ijsbol** [comment]
`/many` requires a post request not a get request
![image](https://github.com/Waifu-pics/waifu-api/assets/57773965/078aaac9-adee-481d-9976-2cb7c04859b7)

**Comment by TusharSharmaIN** [comment]
getting @Isabe1le @JSH32
```
{
    "message": "that was not a valid json body"
}
```
![image](https://github.com/Waifu-pics/waifu-api/assets/32814311/e5fe7711-9bb8-4e73-957f-76edd36514d7)

**Comment by ijsbol** [comment]
What JSON body are you attaching to your request?

**Comment by TusharSharmaIN** [comment]
@Isabe1le issue is resolved now, tried with exclude field in body
