### ISSUE TITLE
Get many images

### ISSUE THREAD

**Issue by Crazyshinobi** [Waifu-pics/waifu-api#81]
While requesting the API to get many images through:

URL: https://api.waifu.pics/many/sfw/happy

Result: 
{
"message": "Method Not Allowed"
}

I have also used POST method:

Result:
{
"message": "that was not a valid json body"
}

**Comment by JSH32** [comment]
You need to use a POST request with an exclude field which is an array of strings
https://waifu.pics/docs

**Comment by Crazyshinobi** [comment]
can you give a example?
