### ISSUE TITLE
waifu.pics domain expired

### ISSUE THREAD

**Issue by faridmovsumov** [Waifu-pics/waifu-api#82]
Seems like the domain is expired. 

![image](https://github.com/Waifu-pics/waifu-api/assets/1541412/00ec394f-fde7-472f-9b71-3c9e23264780)

**Comment by bariscodefxy** [comment]
Yes, I got it too.

**Comment by JSH32** [comment]
Oop, gonna renew one sec lmao

**Comment by bariscodefxy** [comment]
Renewed!
