### ISSUE TITLE
Project still active?

### ISSUE THREAD

**Issue by newtox** [Waifu-pics/waifu-api#83]
The website says the api url got changed? Is this still present?

**Comment by Pandirel** [comment]
> The website says the api url got changed? Is this still present?

According to me he is still alive. But I don't know if they have updated images, in addition to having a super slow page  :c
If it is for Dicord bots, I do not recommend that you use it.

**Comment by JSH32** [comment]
Still alive and being approved occasionally. The page is slow but it's mainly just to preview API content, the API is the main part of this and it's for use primarily for discord bots.
